
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        framePanel = new javax.swing.JPanel();
        imagePanel = new javax.swing.JPanel();
        nuLogo = new javax.swing.JLabel();
        nubImage = new javax.swing.JLabel();
        signupLogoLabel = new javax.swing.JLabel();
        su_passwordLabel = new javax.swing.JLabel();
        su_txtPassword = new javax.swing.JTextField();
        su_txtUsername = new javax.swing.JTextField();
        su_usernameLabel = new javax.swing.JLabel();
        su_signupButton = new javax.swing.JButton();
        su_loginLabel = new javax.swing.JLabel();
        su_loginButton = new javax.swing.JButton();
        su_EmailLabel = new javax.swing.JLabel();
        su_txtEmail = new javax.swing.JTextField();
        minimizeButton = new javax.swing.JLabel();
        exitButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        framePanel.setBackground(new java.awt.Color(255, 255, 255));
        framePanel.setLayout(null);

        imagePanel.setBackground(new java.awt.Color(53, 64, 142));
        imagePanel.setLayout(null);

        nuLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/left (1).png"))); // NOI18N
        nuLogo.setText("jLabel2");
        imagePanel.add(nuLogo);
        nuLogo.setBounds(0, 0, 440, 230);

        nubImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bulldogs.jpg"))); // NOI18N
        nubImage.setText("jLabel1");
        imagePanel.add(nubImage);
        nubImage.setBounds(-330, 230, 770, 370);

        framePanel.add(imagePanel);
        imagePanel.setBounds(460, 0, 440, 600);

        signupLogoLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 60)); // NOI18N
        signupLogoLabel.setForeground(new java.awt.Color(53, 64, 142));
        signupLogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signupLogoLabel.setText("SIGN UP");
        framePanel.add(signupLogoLabel);
        signupLogoLabel.setBounds(90, 50, 280, 70);

        su_passwordLabel.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        su_passwordLabel.setForeground(new java.awt.Color(0, 0, 0));
        su_passwordLabel.setText("PASSWORD:");
        framePanel.add(su_passwordLabel);
        su_passwordLabel.setBounds(40, 370, 110, 20);

        su_txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        su_txtPassword.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        su_txtPassword.setForeground(new java.awt.Color(0, 0, 0));
        su_txtPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        su_txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                su_txtPasswordKeyPressed(evt);
            }
        });
        framePanel.add(su_txtPassword);
        su_txtPassword.setBounds(40, 390, 380, 50);

        su_txtUsername.setBackground(new java.awt.Color(255, 255, 255));
        su_txtUsername.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        su_txtUsername.setForeground(new java.awt.Color(0, 0, 0));
        su_txtUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        su_txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                su_txtUsernameKeyPressed(evt);
            }
        });
        framePanel.add(su_txtUsername);
        su_txtUsername.setBounds(40, 180, 380, 50);

        su_usernameLabel.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        su_usernameLabel.setForeground(new java.awt.Color(0, 0, 0));
        su_usernameLabel.setText("USERNAME:");
        framePanel.add(su_usernameLabel);
        su_usernameLabel.setBounds(40, 160, 110, 20);

        su_signupButton.setBackground(new java.awt.Color(53, 64, 142));
        su_signupButton.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        su_signupButton.setForeground(new java.awt.Color(255, 255, 255));
        su_signupButton.setText("Sign up");
        su_signupButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        su_signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                su_signupButtonActionPerformed(evt);
            }
        });
        framePanel.add(su_signupButton);
        su_signupButton.setBounds(40, 450, 130, 30);

        su_loginLabel.setForeground(new java.awt.Color(102, 102, 102));
        su_loginLabel.setText("Already have an account? Login here:");
        framePanel.add(su_loginLabel);
        su_loginLabel.setBounds(160, 570, 220, 20);

        su_loginButton.setBackground(new java.awt.Color(204, 204, 204));
        su_loginButton.setForeground(new java.awt.Color(0, 0, 0));
        su_loginButton.setText("Login");
        su_loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        su_loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                su_loginButtonActionPerformed(evt);
            }
        });
        framePanel.add(su_loginButton);
        su_loginButton.setBounds(370, 570, 72, 23);

        su_EmailLabel.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        su_EmailLabel.setForeground(new java.awt.Color(0, 0, 0));
        su_EmailLabel.setText("EMAIL:");
        framePanel.add(su_EmailLabel);
        su_EmailLabel.setBounds(40, 260, 110, 20);

        su_txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        su_txtEmail.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        su_txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        su_txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        su_txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                su_txtEmailKeyPressed(evt);
            }
        });
        framePanel.add(su_txtEmail);
        su_txtEmail.setBounds(40, 280, 380, 50);

        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minus.png"))); // NOI18N
        minimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeButtonMouseClicked(evt);
            }
        });
        framePanel.add(minimizeButton);
        minimizeButton.setBounds(50, 0, 32, 40);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close (2).png"))); // NOI18N
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        framePanel.add(exitButton);
        exitButton.setBounds(10, 0, 32, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void su_signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_su_signupButtonActionPerformed
        String username, email, password, query;
        String url, user, pass;

        url = "jdbc:MySQL://localhost:3306/hso_database";
        user = "root";
        pass = "";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, user, pass);
            Statement st = con.createStatement();

            if ("".equals(su_txtUsername.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Username is required to proceed.", "ERROR: Missing Username.", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(su_txtEmail.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Email is required to proceed.", "ERROR: Missing Email.", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(su_txtPassword.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Password is required to proceed.", "ERROR: Missing Password.", JOptionPane.ERROR_MESSAGE);
            } else {
                username = su_txtUsername.getText();
                email = su_txtEmail.getText();
                password = su_txtPassword.getText();

                query = "SELECT * FROM user WHERE username='" + username + "'";
                ResultSet rs = st.executeQuery(query);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(new JFrame(), "Username already exists. Please choose a different username.", "ERROR: Username Exists.", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                query = "SELECT * FROM user WHERE email='" + email + "'";
                rs = st.executeQuery(query);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(new JFrame(), "Email already exists. Please choose a different email.", "ERROR: Email Exists.", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                query = "INSERT INTO user(username, email, password)" + "VALUES('" + username + "', '" + email + "', '" + password + "')";

                st.execute(query);

                su_txtUsername.setText("");
                su_txtEmail.setText("");
                su_txtPassword.setText("");
                JOptionPane.showMessageDialog(null, "Account created successfully!", "Creation Successful!", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            System.out.println("Error!" + e.getMessage());
        }
    }//GEN-LAST:event_su_signupButtonActionPerformed

    private void su_loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_su_loginButtonActionPerformed
        // TODO add your handling code here:
        SignUpLogIn login = new SignUpLogIn();

        login.show();
        dispose();


    }//GEN-LAST:event_su_loginButtonActionPerformed

    private void su_txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_su_txtUsernameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            su_txtEmail.requestFocus();
        }
     }//GEN-LAST:event_su_txtUsernameKeyPressed

    private void su_txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_su_txtEmailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            su_txtPassword.requestFocus();
        }
    }//GEN-LAST:event_su_txtEmailKeyPressed

    private void su_txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_su_txtPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            su_txtUsername.requestFocus();

            String username, email, password, query;
            String url, user, pass;

            url = "jdbc:MySQL://localhost:3306/hso_database";
            user = "root";
            pass = "";

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection(url, user, pass);
                Statement st = con.createStatement();

                if ("".equals(su_txtUsername.getText())) {
                    JOptionPane.showMessageDialog(new JFrame(), "Username is required to proceed.", "ERROR: Missing Username.", JOptionPane.ERROR_MESSAGE);
                } else if ("".equals(su_txtEmail.getText())) {
                    JOptionPane.showMessageDialog(new JFrame(), "Email is required to proceed.", "ERROR: Missing Email.", JOptionPane.ERROR_MESSAGE);
                } else if ("".equals(su_txtPassword.getText())) {
                    JOptionPane.showMessageDialog(new JFrame(), "Password is required to proceed.", "ERROR: Missing Password.", JOptionPane.ERROR_MESSAGE);
                } else {
                    username = su_txtUsername.getText();
                    email = su_txtEmail.getText();
                    password = su_txtPassword.getText();

                    query = "SELECT * FROM user WHERE username='" + username + "'";
                    ResultSet rs = st.executeQuery(query);
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(new JFrame(), "Username already exists. Please choose a different username.", "ERROR: Username Exists.", JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    query = "SELECT * FROM user WHERE email='" + email + "'";
                    rs = st.executeQuery(query);
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(new JFrame(), "Email already exists. Please choose a different email.", "ERROR: Email Exists.", JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    query = "INSERT INTO user(username, email, password)" + "VALUES('" + username + "', '" + email + "', '" + password + "')";

                    st.execute(query);

                    su_txtUsername.setText("");
                    su_txtEmail.setText("");
                    su_txtPassword.setText("");
                    JOptionPane.showMessageDialog(null, "Account created successfully!", "Creation Successful!", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
                System.out.println("Error!" + e.getMessage());
            }
        }
    }//GEN-LAST:event_su_txtPasswordKeyPressed

    private void minimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeButtonMouseClicked
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor((JLabel) evt.getSource());
        frame.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonMouseClicked

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Exit", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitButton;
    private javax.swing.JPanel framePanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel minimizeButton;
    private javax.swing.JLabel nuLogo;
    private javax.swing.JLabel nubImage;
    private javax.swing.JLabel signupLogoLabel;
    private javax.swing.JLabel su_EmailLabel;
    private javax.swing.JButton su_loginButton;
    private javax.swing.JLabel su_loginLabel;
    private javax.swing.JLabel su_passwordLabel;
    private javax.swing.JButton su_signupButton;
    private javax.swing.JTextField su_txtEmail;
    private javax.swing.JTextField su_txtPassword;
    private javax.swing.JTextField su_txtUsername;
    private javax.swing.JLabel su_usernameLabel;
    // End of variables declaration//GEN-END:variables
}
